language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

branches:
  except:
    - /^v[0-9]/

if: tag IS blank

before_install:
  - sed -i -e "s/\"build\":\s[0-9]*/\"build\":"' '"$TRAVIS_BUILD_NUMBER/" component.json

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell
  - sudo apt install docker.io -y
  - sudo usermod -a -G docker $(id -un)
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - sudo mkdir ~/.kube
  - curl -s -o config https://$GITHUB_API_KEY@raw.githubusercontent.com/EgorNuzhnykh/pip-templates-deploy/master/config
  - sudo cp config ~/.kube/config
  # - echo ${KUBE_CONFIG} > ~/.kube/config
  - kubectl get nodes
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script: 
  - ./build.ps1
  - ./test.ps1
  - ./package.ps1
  - ./tag.ps1
  - ./publish.ps1
  - ./release.ps1

after_script:
  - ./clean.ps1
  - rm -rf ./tasks
  - git clone git@github.com:pip-templates/pip-templates-devops-buildtasks.git tasks
  - echo "Deploy into staging environment"
  - ./tasks/deploy.ps1
  - ./tasks/validate.ps1
  - ./tasks/promote.ps1
  - ./tasks/rollback.ps1
  - ./tasks/clean.ps1